<?php
defined('ABSPATH') || exit;
function rema_admin_menu(){add_theme_page(__('Rima Theme Controls','rima-ramroma'),__('Rima Theme Controls','rima-ramroma'),'manage_options','rema-theme','rema_admin_page');}
add_action('admin_menu','rema_admin_menu');
function rema_admin_assets($hook){if($hook!=='appearance_page_rema-theme')return;wp_enqueue_media();wp_enqueue_script('jquery-ui-sortable');wp_enqueue_style('rema-admin',get_template_directory_uri().'/assets/css/admin.css',array(),wp_get_theme()->get('Version'));wp_enqueue_script('rema-admin',get_template_directory_uri().'/assets/js/admin.js',array('jquery','jquery-ui-sortable'),wp_get_theme()->get('Version'),true);}
add_action('admin_enqueue_scripts','rema_admin_assets');
function rema_recursive_sanitize($value){if(is_array($value))return array_map('rema_recursive_sanitize',$value);return wp_kses_post(wp_unslash($value));}
function rema_save_admin(){if(!current_user_can('manage_options')||!check_admin_referer('rema_save_theme'))wp_die(__('Not allowed','rima-ramroma'));$settings=isset($_POST['rema'])?rema_recursive_sanitize($_POST['rema']):array();$settings['section_order']=array_values(array_filter(explode(',',sanitize_text_field($_POST['section_order']??''))));foreach(array('hero','intro','brands','divider','vision','mission','values','lifestyle_family','lifestyle_back') as $id)$settings[$id]['enabled']=isset($_POST['rema'][$id]['enabled'])?1:0;$settings['header']['show']=isset($_POST['rema']['header']['show'])?1:0;$settings['footer']['show']=isset($_POST['rema']['footer']['show'])?1:0;update_option('rema_theme_settings',$settings);wp_safe_redirect(add_query_arg(array('page'=>'rema-theme','updated'=>'1'),admin_url('themes.php')));exit;}
add_action('admin_post_rema_save_theme','rema_save_admin');
function rema_restore_admin(){if(!current_user_can('manage_options')||!check_admin_referer('rema_restore_theme'))wp_die(__('Not allowed','rima-ramroma'));delete_option('rema_theme_settings');wp_safe_redirect(add_query_arg(array('page'=>'rema-theme','restored'=>'1'),admin_url('themes.php')));exit;}
add_action('admin_post_rema_restore_theme','rema_restore_admin');
function rema_admin_input($path,$label,$type='text',$extra=array()){$s=rema_get_settings();$value=rema_array_get($s,$path,'');$name='rema['.str_replace('.','][',$path).']';echo '<div class="rema-field"><label>'.esc_html($label).'</label>';if($type==='editor'){wp_editor($value,'rema_'.str_replace('.','_',$path),array('textarea_name'=>$name,'textarea_rows'=>4,'media_buttons'=>false,'teeny'=>true));}elseif($type==='image'){echo '<div class="rema-media"><input type="url" name="'.esc_attr($name).'" value="'.esc_attr($value).'" placeholder="https://"><button type="button" class="button rema-media-button">'.esc_html__('Choose image','rima-ramroma').'</button><div class="rema-media-preview">'.($value?'<img src="'.esc_url($value).'" alt="">':'').'</div></div>';}elseif($type==='checkbox'){echo '<label class="rema-switch"><input type="checkbox" name="'.esc_attr($name).'" value="1" '.checked($value,1,false).'><span>'.esc_html__('Enabled','rima-ramroma').'</span></label>';}elseif($type==='select'){echo '<select name="'.esc_attr($name).'">';foreach($extra as $k=>$v)echo '<option value="'.esc_attr($k).'" '.selected($value,$k,false).'>'.esc_html($v).'</option>';echo '</select>';}else echo '<input type="'.esc_attr($type).'" name="'.esc_attr($name).'" value="'.esc_attr($value).'">';echo '</div>';}
function rema_admin_section($id,$label,$fields){echo '<section class="rema-panel" id="panel-'.esc_attr($id).'"><h2>'.esc_html($label).'</h2>';if(!in_array($id,array('typography','colors'),true))rema_admin_input($id.'.enabled',__('Display section','rima-ramroma'),'checkbox');foreach($fields as $field)rema_admin_input($id.'.'.$field[0],$field[1],$field[2]??'text',$field[3]??array());echo '</section>';}
function rema_admin_page(){if(!current_user_can('manage_options'))return;$s=rema_get_settings();$labels=array('hero'=>'Hero','intro'=>'Introduction','brands'=>'Brands','divider'=>'BabeChic divider','vision'=>'Vision','mission'=>'Mission','values'=>'Values','lifestyle_family'=>'Regional lifestyle','lifestyle_back'=>'Journey banner');?>
<div class="wrap rema-admin"><div class="rema-admin-head"><div><h1><?php esc_html_e('Rima Theme Controls','rima-ramroma');?></h1><p><?php esc_html_e('Edit, reorder and preview the Figma-based Rima page. Rich text is registered with Polylang under Languages → Translations.','rima-ramroma');?></p></div><a class="button button-secondary" target="_blank" href="<?php echo esc_url(home_url('/?rema_preview=1'));?>"><?php esc_html_e('Open full preview','rima-ramroma');?></a></div><?php if(isset($_GET['updated']))echo '<div class="notice notice-success"><p>'.esc_html__('Settings saved.','rima-ramroma').'</p></div>';if(isset($_GET['restored']))echo '<div class="notice notice-success"><p>'.esc_html__('Figma defaults restored.','rima-ramroma').'</p></div>';?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="rema_save_theme"><?php wp_nonce_field('rema_save_theme');?><div class="rema-admin-grid"><aside><nav class="rema-nav"><a href="#panel-order">Section order</a><a href="#panel-header">Header</a><?php foreach($labels as $id=>$label)echo '<a href="#panel-'.esc_attr($id).'">'.esc_html($label).'</a>';?><a href="#panel-footer">Footer</a><a href="#panel-typography">Typography</a><a href="#panel-colors">Colors</a><a href="#panel-preview">Preview</a></nav></aside><div class="rema-panels">
<section class="rema-panel" id="panel-order"><h2><?php esc_html_e('Section order','rima-ramroma');?></h2><p><?php esc_html_e('Drag sections into the desired order.','rima-ramroma');?></p><ul id="rema-sortable"><?php foreach($s['section_order'] as $id)echo '<li data-id="'.esc_attr($id).'"><span class="dashicons dashicons-move"></span>'.esc_html($labels[$id]??$id).'</li>';?></ul><input type="hidden" id="section_order" name="section_order" value="<?php echo esc_attr(implode(',',$s['section_order']));?>"></section>
<section class="rema-panel" id="panel-header"><h2><?php esc_html_e('Header','rima-ramroma');?></h2><?php rema_admin_input('header.show','Display header','checkbox');rema_admin_input('header.about_label','About label','editor');rema_admin_input('header.about_url','About link','url');rema_admin_input('header.brands_label','Brands label','editor');rema_admin_input('header.brands_url','Brands link','url');rema_admin_input('header.shop_label','Shop label','editor');rema_admin_input('header.shop_url','Shop link','url');rema_admin_input('header.logo_image','Rima logo override','image');rema_admin_input('header.ramroma_logo_image','Ramroma logo','image');?></section>
<?php rema_admin_section('hero','Hero',array(array('image','Background image','image'),array('title','Title','editor'),array('button','Button text','editor'),array('url','Button link','url')));rema_admin_section('intro','Introduction',array(array('title','Title','editor'),array('text','Body','editor')));rema_admin_section('brands','Brands',array(array('title','Title','editor'),array('rima_image','Rima image','image'),array('rima_text','Rima text','editor'),array('ramroma_image','Ramroma image','image'),array('ramroma_text','Ramroma text','editor')));rema_admin_section('divider','BabeChic divider',array(array('text','Text','editor'),array('logo','Logo','image')));rema_admin_section('vision','Vision',array(array('image','Background image','image'),array('title','Title','editor'),array('text','Body','editor')));?>
<section class="rema-panel" id="panel-mission"><h2>Mission</h2><?php rema_admin_input('mission.enabled','Display section','checkbox');rema_admin_input('mission.title','Title','editor');foreach($s['mission']['items'] as $i=>$item){echo '<fieldset><legend>Card '.($i+1).'</legend>';rema_admin_input('mission.items.'.$i.'.image','Image','image');rema_admin_input('mission.items.'.$i.'.title','Title','editor');rema_admin_input('mission.items.'.$i.'.text','Text','editor');echo '</fieldset>';}?></section>
<section class="rema-panel" id="panel-values"><h2>Values</h2><?php rema_admin_input('values.enabled','Display section','checkbox');rema_admin_input('values.title','Title','editor');foreach($s['values']['items'] as $i=>$item){echo '<fieldset><legend>Value '.($i+1).'</legend>';rema_admin_input('values.items.'.$i.'.label','Label','text');rema_admin_input('values.items.'.$i.'.type','Visual type','select',array('icon'=>'Font Awesome icon','image'=>'Uploaded image'));rema_admin_input('values.items.'.$i.'.icon','Icon class','text');rema_admin_input('values.items.'.$i.'.image','Image','image');echo '</fieldset>';}?></section>
<?php rema_admin_section('lifestyle_family','Regional lifestyle',array(array('image','Background image','image'),array('title','Title','editor'),array('text','Body','editor'),array('button','Button','editor'),array('url','Link','url')));rema_admin_section('lifestyle_back','Journey banner',array(array('image','Background image','image'),array('title','Title','editor'),array('text','Body','editor'),array('button','Button','editor'),array('url','Link','url')));?>
<section class="rema-panel" id="panel-footer"><h2>Footer</h2><?php rema_admin_input('footer.show','Display footer','checkbox');rema_admin_input('footer.about','About text','editor');rema_admin_input('footer.follow','Social heading','editor');rema_admin_input('footer.quick','Links heading','editor');foreach($s['footer']['links'] as $i=>$item){echo '<fieldset><legend>Link '.($i+1).'</legend>';rema_admin_input('footer.links.'.$i.'.label','Label','text');rema_admin_input('footer.links.'.$i.'.url','URL','url');echo '</fieldset>';}foreach($s['footer']['socials'] as $i=>$item){echo '<fieldset><legend>Social '.($i+1).'</legend>';rema_admin_input('footer.socials.'.$i.'.label','Accessible label','text');rema_admin_input('footer.socials.'.$i.'.url','URL','url');rema_admin_input('footer.socials.'.$i.'.type','Visual type','select',array('icon'=>'Font Awesome icon','image'=>'Uploaded image'));rema_admin_input('footer.socials.'.$i.'.icon','Icon class','text');rema_admin_input('footer.socials.'.$i.'.image','Image','image');echo '</fieldset>';}rema_admin_input('footer.copyright','Copyright','editor');?></section>
<?php rema_admin_section('typography','Responsive font sizes',array(array('heading_desktop','Heading desktop (px)','number'),array('heading_tablet','Heading tablet (px)','number'),array('heading_mobile','Heading mobile (px)','number'),array('hero_desktop','Hero desktop (px)','number'),array('hero_tablet','Hero tablet (px)','number'),array('hero_mobile','Hero mobile (px)','number'),array('body_desktop','Body desktop (px)','number'),array('body_tablet','Body tablet (px)','number'),array('body_mobile','Body mobile (px)','number')));rema_admin_section('colors','Theme colors',array(array('ink','Primary text','color'),array('muted','Muted text','color'),array('soft','Soft background','color'),array('footer','Footer background','color'),array('white','Light text','color')));?>
<section class="rema-panel" id="panel-preview"><h2><?php esc_html_e('Live preview','rima-ramroma');?></h2><p><?php esc_html_e('Save changes, then refresh this preview.','rima-ramroma');?></p><div class="rema-preview-toolbar"><button type="button" data-width="100%">Desktop</button><button type="button" data-width="768px">Tablet</button><button type="button" data-width="390px">Mobile</button></div><iframe id="rema-preview" src="<?php echo esc_url(home_url('/?rema_preview=1'));?>" title="Rima page preview"></iframe></section>
<p class="submit"><button class="button button-primary button-hero" type="submit"><?php esc_html_e('Save theme controls','rima-ramroma');?></button></p></div></div></form><form class="rema-restore" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return confirm('<?php echo esc_js(__('Restore every setting and image to the original Figma defaults?','rima-ramroma'));?>');"><input type="hidden" name="action" value="rema_restore_theme"><?php wp_nonce_field('rema_restore_theme');?><button class="button button-link-delete" type="submit"><?php esc_html_e('Restore Figma defaults','rima-ramroma');?></button></form></div><?php }
