<?php
defined('ABSPATH') || exit;
function rema_default_settings(){
 $img=get_template_directory_uri().'/assets/images/';
 return array(
  'section_order'=>array('hero','intro','brands','divider','vision','mission','values','lifestyle_family','lifestyle_back'),
  'header'=>array('show'=>1,'about_label'=>'About Us','about_url'=>'#intro','brands_label'=>'Brands','brands_url'=>'#brands','shop_label'=>'SHOP','shop_url'=>'#shop','account_label'=>'Hi, ROSE','logo_image'=>'','ramroma_logo_image'=>$img.'ramroma-logo.png','search_url'=>'/?s=','cart_url'=>'/cart/','account_url'=>'/my-account/'),
  'hero'=>array('enabled'=>1,'image'=>$img.'hero.jpg','title'=>'<span class="rema-script">Unleash</span> Your Power.<br><span class="rema-script">Own</span> Your Motion.','button'=>'Shop the Collection','url'=>'#shop'),
  'intro'=>array('enabled'=>1,'title'=>'Premium Activewear for Women &amp; Girls Across the Middle East','text'=>'Move with confidence, style, and elegance in every step.<br>Discover <strong>Rima &amp; Ramroma</strong>, part of the <strong>BabeChic</strong> collection, bringing world-class sportswear to the GCC, MENA region, and North Africa.'),
  'brands'=>array('enabled'=>1,'title'=>'Where <span class="rema-script">Elegance</span> Meets Energy','rima_image'=>$img.'brand-rima.jpg','ramroma_image'=>$img.'brand-ramroma.jpg','rima_text'=>'Inspired by Al Reem (Gizalla Al Reem), blends elegance, strength, and grace in activewear for women.','ramroma_text'=>'Ramroma, a playful nickname of Rima, celebrates energy, joy, and creativity in girls’ activewear, inspiring confidence and self-expression.','rima_button'=>'Explore the Collection','rima_url'=>'#shop-rima','ramroma_button'=>'Explore the Collection','ramroma_url'=>'#shop-ramroma'),
  'divider'=>array('enabled'=>1,'text'=>'From the House of','logo'=>$img.'babechic-logo.png'),
  'vision'=>array('enabled'=>1,'image'=>$img.'vision.jpg','title'=>'Our Vision: Inspire Active Lives','text'=>'“Leading the MENA women’s activewear market with high-performance, trendy designs that support Saudi Arabia’s Quality of Life goals and Vision 2030.”'),
  'mission'=>array('enabled'=>1,'title'=>'Our Mission: Move, Play, Shine','items'=>array(array('image'=>$img.'mission-premium.jpg','title'=>'Premium Activewear:','text'=>'Stylish, comfortable designs for women and girls.'),array('image'=>$img.'mission-empowerment.jpg','title'=>'Empowerment:','text'=>'Boosting confidence, joy, and self-expression.'),array('image'=>$img.'mission-wellness.jpg','title'=>'Wellness:','text'=>'Encouraging active, healthy lifestyles.'))),
  'values'=>array('enabled'=>1,'title'=>'Our Values: Style. Performance. Empowerment.','items'=>array(array('type'=>'icon','icon'=>'fa-solid fa-gem','image'=>'','label'=>'Quality'),array('type'=>'icon','icon'=>'fa-solid fa-wand-magic-sparkles','image'=>'','label'=>'Style'),array('type'=>'icon','icon'=>'fa-solid fa-building-shield','image'=>'','label'=>'Empowerment'),array('type'=>'icon','icon'=>'fa-solid fa-person-running','image'=>'','label'=>'Playfulness'),array('type'=>'icon','icon'=>'fa-solid fa-leaf','image'=>'','label'=>'Sustainability'))),
  'lifestyle_family'=>array('enabled'=>1,'image'=>$img.'lifestyle-family.jpg','title'=>'Designed for Our Region','text'=>'From the Gulf to North Africa, Rima &amp; Ramroma move with you. Breathable fabrics, modest-friendly fits, and stylish designs for active, confident lifestyles.','button'=>'','url'=>''),
  'lifestyle_back'=>array('enabled'=>1,'image'=>$img.'lifestyle-back.jpg','title'=>'Move Freely.<br>Play Boldly.<br>Shine Always.','text'=>'','button'=>'Start Your Journey','url'=>'#shop'),
  'footer'=>array('show'=>1,'about'=>'Start your active lifestyle journey with Rima &amp; Ramroma, designed for women and girls across the GCC, MENA, and North Africa.','follow'=>'Follow Us','quick'=>'QUICK LINKS','links'=>array(array('label'=>'Shop Rima','url'=>'#shop-rima'),array('label'=>'Shop Ramroma','url'=>'#shop-ramroma'),array('label'=>'Our Story','url'=>'#intro'),array('label'=>'Size Guide','url'=>'#size-guide'),array('label'=>'Contact Us','url'=>'#contact')),'socials'=>array(array('label'=>'X / Twitter','url'=>'#','type'=>'icon','icon'=>'fa-brands fa-x-twitter','image'=>''),array('label'=>'Instagram','url'=>'#','type'=>'icon','icon'=>'fa-brands fa-instagram','image'=>''),array('label'=>'Facebook','url'=>'#','type'=>'icon','icon'=>'fa-brands fa-facebook-f','image'=>''),array('label'=>'YouTube','url'=>'#','type'=>'icon','icon'=>'fa-brands fa-youtube','image'=>'')),'copyright'=>'© 2026 Rima &amp; Ramroma. All rights reserved.<br>Part of the BabeChic Collection.'),
  'typography'=>array('heading_desktop'=>36,'heading_tablet'=>30,'heading_mobile'=>24,'hero_desktop'=>36,'hero_tablet'=>32,'hero_mobile'=>26,'body_desktop'=>16,'body_tablet'=>15,'body_mobile'=>14),
  'colors'=>array('ink'=>'#293042','muted'=>'#5c5c5c','soft'=>'#f5f5f5','footer'=>'#1b2124','white'=>'#ffffff')
 );
}
