<?php
defined('ABSPATH') || exit;
function rema_btn($label,$url,$light=false){if(!$label)return '';return '<a class="btn rema-btn '.($light?'rema-btn-light':'rema-btn-dark').'" href="'.esc_url($url?:'#').'">'.wp_kses_post(rema_t($label)).' <i class="fa-solid fa-arrow-right-long"></i></a>';}
function rema_section_hero(){if(!rema_section_enabled('hero'))return '';ob_start();?><section id="hero" class="rema-hero" style="--rema-bg:url('<?php echo rema_asset('hero.image');?>')"><div class="container h-100"><div class="rema-hero-content"><h1><?php echo wp_kses_post(rema_content('hero.title'));?></h1><?php echo rema_btn(rema_content('hero.button'),rema_content('hero.url'),true);?></div></div></section><?php return ob_get_clean();}
function rema_section_intro(){if(!rema_section_enabled('intro'))return '';ob_start();?><section id="intro" class="rema-intro section-pad"><div class="container"><h2><?php echo wp_kses_post(rema_content('intro.title'));?></h2><div class="rema-copy"><?php echo wp_kses_post(rema_content('intro.text'));?></div></div></section><?php return ob_get_clean();}
function rema_brand_logo($kind){$img=get_template_directory_uri().'/assets/images/';if($kind==='rima')return '<span class="rema-brand-logo rema-brand-rima"><img src="'.esc_url($img.'rima-logo-mark.svg').'" alt=""><img src="'.esc_url($img.'rima-logo-word.svg').'" alt="Rima"></span>';return '<img class="rema-brand-logo rema-ramroma-logo" src="'.esc_url($img.'ramroma-logo.png').'" alt="Ramroma">';}
function rema_section_brands(){if(!rema_section_enabled('brands'))return '';ob_start();?><section id="brands" class="rema-brands section-pad"><div class="container"><h2><?php echo wp_kses_post(rema_content('brands.title'));?></h2><div class="row g-4 mt-1"><div class="col-lg-6"><article class="rema-brand-card"><img src="<?php echo rema_asset('brands.rima_image');?>" alt="Rima"><div class="rema-brand-copy"><?php echo rema_brand_logo('rima');?><p><?php echo wp_kses_post(rema_content('brands.rima_text'));?></p></div></article></div><div class="col-lg-6"><article class="rema-brand-card rema-brand-card-ramroma"><img src="<?php echo rema_asset('brands.ramroma_image');?>" alt="Ramroma"><div class="rema-brand-copy"><?php echo rema_brand_logo('ramroma');?><p><?php echo wp_kses_post(rema_content('brands.ramroma_text'));?></p></div></article></div></div></div></section><?php return ob_get_clean();}
function rema_section_divider(){if(!rema_section_enabled('divider'))return '';$logo=rema_asset('divider.logo');if(strpos($logo,'babechic-logo.png')!==false)$logo='';ob_start();?><section class="rema-divider"><div class="container d-flex align-items-center justify-content-center gap-3"><span></span><p><?php echo wp_kses_post(rema_content('divider.text'));?></p><?php if($logo):?><img src="<?php echo esc_url($logo);?>" alt="BabeChic"><?php else:?><strong class="rema-babechic">BabeChic<small>Collection</small></strong><?php endif;?><span></span></div></section><?php return ob_get_clean();}
function rema_section_vision(){if(!rema_section_enabled('vision'))return '';ob_start();?><section id="vision" class="rema-vision" style="--rema-bg:url('<?php echo rema_asset('vision.image');?>')"><div class="container"><div class="rema-banner-copy"><h2><?php echo wp_kses_post(rema_content('vision.title'));?></h2><p><?php echo wp_kses_post(rema_content('vision.text'));?></p></div></div></section><?php return ob_get_clean();}
function rema_section_mission(){if(!rema_section_enabled('mission'))return '';$s=rema_get_settings();ob_start();?><section id="mission" class="rema-mission section-pad"><div class="container"><h2><?php echo wp_kses_post(rema_content('mission.title'));?></h2><div class="row g-4 mt-1"><?php foreach($s['mission']['items'] as $item):?><div class="col-md-4"><article class="rema-mission-card"><img src="<?php echo esc_url($item['image']);?>" alt="<?php echo esc_attr(wp_strip_all_tags(rema_t($item['title'])));?>"><h3><?php echo wp_kses_post(rema_t($item['title']));?></h3><p><?php echo wp_kses_post(rema_t($item['text']));?></p></article></div><?php endforeach;?></div></div></section><?php return ob_get_clean();}
function rema_section_values(){if(!rema_section_enabled('values'))return '';$s=rema_get_settings();ob_start();?><section id="values" class="rema-values section-pad"><div class="container"><h2><?php echo wp_kses_post(rema_content('values.title'));?></h2><div class="rema-values-grid"><?php foreach($s['values']['items'] as $item):?><div class="rema-value"><?php echo rema_icon_or_image($item,'rema-value-icon');?><span><?php echo esc_html(rema_t($item['label']));?></span></div><?php endforeach;?></div></div></section><?php return ob_get_clean();}
function rema_section_lifestyle($id){if(!rema_section_enabled($id))return '';$family=$id==='lifestyle_family';ob_start();?><section id="<?php echo esc_attr($id);?>" class="rema-lifestyle <?php echo $family?'rema-lifestyle-family':'rema-lifestyle-back';?>" style="--rema-bg:url('<?php echo rema_asset($id.'.image');?>')"><div class="rema-lifestyle-shade"></div><div class="container position-relative"><div class="rema-lifestyle-copy"><h2><?php echo wp_kses_post(rema_content($id.'.title'));?></h2><?php if(rema_content($id.'.text')):?><p><?php echo wp_kses_post(rema_content($id.'.text'));?></p><?php endif;?><?php echo rema_btn(rema_content($id.'.button'),rema_content($id.'.url'),true);?></div></div></section><?php return ob_get_clean();}
function rema_render_page(){ $s=rema_get_settings();$map=array('hero'=>'rema_section_hero','intro'=>'rema_section_intro','brands'=>'rema_section_brands','divider'=>'rema_section_divider','vision'=>'rema_section_vision','mission'=>'rema_section_mission','values'=>'rema_section_values','lifestyle_family'=>function(){return rema_section_lifestyle('lifestyle_family');},'lifestyle_back'=>function(){return rema_section_lifestyle('lifestyle_back');});$out='<main class="rema-page">';foreach($s['section_order'] as $id)if(isset($map[$id]))$out.=call_user_func($map[$id]);return $out.'</main>';}
add_shortcode('rema_hero','rema_section_hero');add_shortcode('rema_intro','rema_section_intro');add_shortcode('rema_brands','rema_section_brands');add_shortcode('rema_divider','rema_section_divider');add_shortcode('rema_vision','rema_section_vision');add_shortcode('rema_mission','rema_section_mission');add_shortcode('rema_values','rema_section_values');add_shortcode('rema_lifestyle_family',function(){return rema_section_lifestyle('lifestyle_family');});add_shortcode('rema_lifestyle_back',function(){return rema_section_lifestyle('lifestyle_back');});add_shortcode('rema_rima_page','rema_render_page');
